HiveCare1/Models/Apiary.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using HiveCare1.Models.Partials;

namespace HiveCare1.Models
{
    public class Apiary : CreatorPartial,IUserDevider
    {
        [Key] public int ApiaryId { get; set; }
        public string Name { get; set; }
        
        public virtual ICollection<Location> Locations { get; set; }

        public virtual ICollection<ApiaryApplicationUser> Users { get; set; } = new List<ApiaryApplicationUser>();

        [NotMapped] public List<ApplicationUser> Admins { get => Users?.Where(x => x.IsAdmin).Select(x => x.ApplicationUser).ToList(); }
        [NotMapped] public List<ApplicationUser> Beekeepers { get => Users?.Where(x => !x.IsAdmin).Select(x => x.ApplicationUser).ToList(); }
        [NotMapped] public List<HiveYieldAmount> Yields { get => Locations?.SelectMany(x => x.Hives).SelectMany(hive => hive.YieldAmounts).ToList(); }
    }

}

HiveCare1/Areas/Identity/Pages/AdminPage/Edit.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using HiveCare1.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HiveCare1.Areas.Identity.Pages.AdminPage
{
    public class EditModel : PageModel
    {
        private readonly ApplicationUserManager _userManager;


        public EditModel(
            ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }

        //public EditModel(
        //    ApplicationUserManager userManager,
        //    ApplicationUsers user)
        //{
        //    _userManager = userManager;
        //    Input = new InputModel();
        //    Input.Email = user.Email;
        //    Input.City = user.City;
        //    Input.ConfirmPassword = user.Password;
        //    Input.Password = user.Password;
        //    Input.Familyname = user.Familyname;
        //    Input.Firstname = user.Firstname;
        //    Input.HouseNo = user.HouseNo;
        //    Input.Street = user.Street;
        //    Input.Zip = Input.Zip;
        //}

        [BindProperty] public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null)
                {
                    return BadRequest();
                }
                user.UserName = Input.Email;
                user.Email = Input.Email ?? user.Email;
                user.Zip = Input.Zip?? user.Zip;
                user.Firstname = Input.Firstname ?? user.Firstname;
                user.Familyname = Input.Familyname ?? user.Familyname;
                user.City = Input.City ?? user.City;
                user.Street = Input.Street ?? user.Street;
                user.HouseNo = Input.HouseNo ?? user.HouseNo;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded) return LocalRedirect(returnUrl);

                foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }

        public async Task<IActionResult> OnGetAsync(string email)
        {
            var user = await _userManager.FindByEmailAsync(email);
            if (user == null) return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            Input = new InputModel
            {
                Email = email,
                City = user.City,
                Street = user.Street,
                Familyname = user.Familyname,
                Firstname = user.Firstname,
                Zip = user.Zip,
                HouseNo = user.HouseNo
            };

            return Page();
        }

        public class InputModel
        {
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
                MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            [Display(Name = "First Name")]
            public string Firstname { get; set; }

            [Display(Name = "Name")] public string Familyname { get; set; }

            [Display(Name = "Street")] public string Street { get; set; }

            [Display(Name = "Number")] public string HouseNo { get; set; }

            [Display(Name = "City")] public string City { get; set; }

            [Display(Name = "ZIP")] public string Zip { get; set; }
            [Display(Name = "Imkereien")] public List<int> Apiaries { get; set; }

            [Display(Name = "Standorte")] public List<int> Locations { get; set; }
            [Display(Name = "Bienenvölker")] public List<int> Hives { get; set; }
            public ApplicationUser Creator { get; set; }
        }
    }
}

HiveCare1/Controllers/ApiariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using HiveCare1.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

namespace HiveCare1.Models
{
    public class ApiariesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ApplicationUserManager _userManager;
        private readonly ClaimsPrincipal _caller;

        public ApiariesController(ApplicationDbContext context, ApplicationUserManager userManager,
            IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _userManager = userManager;
            _caller = httpContextAccessor.HttpContext.User;
        }

        // GET: Apiaries
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetCurrentUserAsync();
            var isSu = await _userManager.IsInRoleAsync(user, "Superuser");
            return View(await _context.Apiaries
                .Include(apiary => apiary.Locations)
                .ThenInclude(x => x.Hives)
                .ThenInclude(x => x.YieldAmounts)
                .ThenInclude(x => x.Yield)
                .Include(apiary => apiary.Locations)
                .ThenInclude(location => location.Users)
                .ThenInclude(applicationUser => applicationUser.ApplicationUser)
                .Include(apiary => apiary.Users)
                .ThenInclude(applicationUser => applicationUser.ApplicationUser)
                .Where(x => x.Admins.Contains(user) || isSu || x.Locations.SelectMany(y => y.Admins).Contains(user))
                .ToListAsync()
            );
        }

        // GET: Apiaries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var apiary = await _context.Apiaries
                .FirstOrDefaultAsync(m => m.ApiaryId == id);
            if (apiary == null) return NotFound();

            return View(apiary);
        }

        // GET: Apiaries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Apiaries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ApiaryId,Name")] Apiary apiary)
        {
            if (ModelState.IsValid)
            {

                apiary.Creator = await _userManager.GetCurrentUserAsync();
                apiary.CreatorId = apiary.Creator.Id;
                apiary.CreationDate = DateTime.Now;
                apiary.Users = new List<ApiaryApplicationUser>();
                await SetUsers(apiary);
                _context.Add(apiary);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Edit), new {id = apiary.ApiaryId});
            }

            return View(apiary);
        }

        // GET: Apiaries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            
            var apiary = await _context.Apiaries
                .Include(a => a.Creator)
                .Include(a => a.Locations)
                .ThenInclude(location => location.Hives)
                .Include(b => b.Users)
                .ThenInclude(x => x.ApplicationUser).SingleOrDefaultAsync(x => x.ApiaryId == id);
            if (apiary == null) return NotFound();
            return View(apiary);
        }

        // POST: Apiaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ApiaryId,Name")] Apiary apiary)
        {
            if (id != apiary.ApiaryId) return NotFound();
            
            var apiaryName = apiary.Name;
            var apiaryId = apiary.ApiaryId;

            if (ModelState.IsValid)
            {
                var modelToEdit = await _context.Apiaries
                    .Include(ap => ap.Users)
                    .ThenInclude(x => x.ApplicationUser)
                    .Where(api => api.ApiaryId == apiary.ApiaryId)
                    .FirstOrDefaultAsync();
                
                if (modelToEdit == null) return NotFound();

                await SetUsers(modelToEdit);


                if (apiaryName != modelToEdit.Name)
                {
                    modelToEdit.Name = apiary.Name;
                }

                var result = await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Edit), new { id = apiary.ApiaryId });
            }
            return View(apiary);
        }

        private async Task<int> SetUsers(Apiary modelToEdit)
        {
            
            var adminEmails = Request.Form["AdminUsers"].ToString().Split(',').Where(x => x != "").ToList();
            var beekeeperEmails = Request.Form["BeekeeperUsers"].ToString().Trim(',').Split(',').Where(x => x != "").ToList();
            var dellist = modelToEdit.Users.Where( user =>
                !adminEmails.Contains(user.ApplicationUser.Email) ||
                !beekeeperEmails.Contains(user.ApplicationUser.Email)).ToList();

            foreach (var applicationUser in dellist)
                modelToEdit.Users.Remove(applicationUser);

            foreach (var adminEmail in adminEmails)
            {
                var admin = await _userManager.FindByEmailAsync(adminEmail);
                modelToEdit.Users.Add(new ApiaryApplicationUser()
                {
                    ApplicationUser = admin,
                    ApplicationUserId = admin.Id,
                    Apiary = modelToEdit,
                    ApiaryId = modelToEdit.ApiaryId,
                    IsAdmin = true
                });
            }
            foreach (var email in beekeeperEmails)
            {
                var beekeeper = await _userManager.FindByEmailAsync(email);
                modelToEdit.Users.Add(new ApiaryApplicationUser()
                {
                    ApplicationUser = beekeeper,
                    ApplicationUserId = beekeeper.Id,
                    Apiary = modelToEdit,
                    ApiaryId = modelToEdit.ApiaryId,
                    IsAdmin = false
                });
            }
            var users = modelToEdit.Users;
            var breakfix = 0;
            return 0;
        }

        // GET: Apiaries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var apiary = await _context.Apiaries
                .FirstOrDefaultAsync(m => m.ApiaryId == id);
            if (apiary == null) return NotFound();

            return View(apiary);
        }

        // POST: Apiaries/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var apiary = await _context.Apiaries.FindAsync(id);
            _context.Apiaries.Remove(apiary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApiaryExists(int id)
        {
            return _context.Apiaries.Any(e => e.ApiaryId == id);
        }

        public async Task<IEnumerable<SelectListItem>> GetListAsync()
        {
            var user = await _userManager.GetCurrentUserAsync();
            return user.Apiaries.Select(x => x.Apiary).Select(x => new SelectListItem(x.Name, x.ApiaryId + ""));
        }

        public async Task<ICollection<Apiary>> ListApiariesAsync()
        {
            var user = await _userManager.GetCurrentUserAsync();
            var isSu = await _userManager.IsInRoleAsync(user, "Superuser");
            return await _context.Apiaries
                .Include(apiary => apiary.Users)
                .Include(apiary => apiary.Creator)
                .Include(apiary => apiary.Locations)
                .ThenInclude(location => location.Hives)
                .Where(apiary => apiary.Users.Any(admin => admin.ApplicationUserId == user.Id) ||
                                 apiary.Creator.Id == user.Id || isSu )
                .ToListAsync();
        }
    }
}

HiveCare1/Views/Apiaries/Create.cshtml
@using HiveCare1.Controllers
@using Microsoft.AspNetCore.Identity
@model Apiary

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}
@inject LocationsController LocationsController
@inject ApplicationUserManager UserManager
<h2>Imkerei erstellen</h2>
<hr/>
<div class="row">
    <div class="col offset-md-2 col-md-8  p-4 shadow flex-grow-1">
        <form id="ApiariesCreate" asp-action="Create" asp-controller="Apiaries">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                    <label>Administratoren:</label>
                    @{await Html.RenderPartialAsync("_AdministratorsSelect", new List<ApplicationUser>()); }
                    <label>Imker:</label>
                    @{await Html.RenderPartialAsync("_BeekeepersSelect", new List<ApplicationUser>()); }
                
            </div>
            <div class="form-group">
                <span class="font-weight-bold"><input type="checkbox" checked="checked" name="Redirect" value="createlocations" /> Nach dem Erstellen, Standorte hinzufügen</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Erstellen" class="btn btn-primary" />
            </div>
        </form>
        <a asp-action="Index">Zurück zur Liste</a>
    </div>
    <div class="d-none d-md-flex col-md-8">

    </div>
</div>

<div>
    
</div>

@section ScriptsBody
{
    <script type="text/javascript">
        $(document).ready(function() {
            var users = [
                @{
                    if (Model != null)
                    {
                        foreach (var user in Model.Users.Select(x => x.ApplicationUser))
                        {
                            var str = "'" + user.Email + "',";
                            @Html.Raw(str)
                        }
                    }
                }];
            $("#addUser").on("click",
                function(e) {
                    e.preventDefault();
                    var newObj = { name: $("#Users option:selected").text(), value: $("#Users").val() };
                    if (!users.some(el => el.value == newObj.value)) {
                        $("#AdminList").append(`<li>${newObj.name}</li>`);
                        users.push(newObj);
                    }

                    const ids = users.map(function(v) {
                        return v.value;
                    });
                    $("#adminuserlist").val(ids.join(';'));

                });
        });
    </script>
}

HiveCare1/Views/Apiaries/Delete.cshtml
@model Apiary

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Apiaries</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ApiaryId"/>
        <input type="submit" value="Delete" class="btn btn-default"/> |
        <a asp-action="Index">Zurück zur Liste</a>
    </form>
</div>

HiveCare1/Views/Apiaries/Details.cshtml
@model Apiary

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Apiaries</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ApiaryId">Edit</a> |
    <a asp-action="Index">Zurück zur Liste</a>
</div>

HiveCare1/Views/Apiaries/Edit.cshtml
@using HiveCare1.Controllers
@using Microsoft.AspNetCore.Identity
@using Microsoft.EntityFrameworkCore
@using Microsoft.EntityFrameworkCore.Internal
@using Microsoft.Extensions.Configuration
@model Apiary
@inject LocationsController LocationsController
@inject ApplicationUserManager UserManager
@inject IConfiguration Configuration
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
    var users = await UserManager.Users.ToListAsync();
    var currentuser = users.First(x => x.UserName == User.Identity.Name);
}

<h2>Imkerei bearbeiten</h2>
<hr />
<div class="row">
    <div class="col-12">

        <div class="container-fluid ">
            <div class="row">
                <div class="col offset-md-2 col-md-8  p-4 shadow flex-grow-1">
                    <form asp-action="Edit" id="ApiariesEdit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="ApiaryId" />
                        <input type="hidden" asp-for="CreatorId" />
                        <input type="hidden" asp-for="CreationDate" />
                        <input type="hidden" asp-for="ApiaryId" />
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label>Administratoren:</label>
                                @{
                                    await Html.RenderPartialAsync("_AdministratorsSelect", Model.Admins);
                                }
                                <hr />
                                <label>Imker:</label>
                                @{
                                    await Html.RenderPartialAsync("_BeekeepersSelect", Model.Beekeepers);
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Speichern" class="btn btn-primary shadow" />
                        </div>
                    </form>
                </div>
                <div class="col col-md-8 offset-md-2 border-light p-4">
                    <h5>Standorte</h5>
                    @{
                        @Html.ActionLink("Neuen Standort erstellen", "Create", "Locations", new { apiaryid = Model.ApiaryId });
                    }


                    @{
                        await Html.RenderPartialAsync("_LocationsList", Model.Locations.ToList());
                    }
                </div>
                @if (Model.Locations.Count > 0)
                {
                    <div class="col col-md-8 offset-md-2 border-light p-4 mt-2">
                        <h5>Bienenvölker</h5>
                        @{
                            @Html.ActionLink("Neues Bienenvolk erstellen", "Create", "Hives", new {locationid = Model.Locations.First().LocationId, apiaryid = Model.ApiaryId})
                            ;
                        }

                        @{
                            await Html.RenderPartialAsync("_HivesList", Model.Locations.SelectMany(x => x.Hives).ToList());
                        }
                    </div>
                }

            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Zurück zur Liste</a>
</div>

@section ScriptsBody
    {
    <script type="text/javascript">
        $(document).ready(function() {
            $("#ApiariesEdit #Administrators").selectpicker('val', [
                    @(Json.Serialize(Model.Users.Select(x => x.ApplicationUser.Email)))
            ]);
            $('#ApiariesEdit #Administrators').selectpicker('refresh');
        });
    </script>
}

HiveCare1/Views/Apiaries/Index.cshtml
@model IEnumerable<Apiary>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}

<h2>Imkereien</h2>

<p>
    <a asp-action="Create">Neue Imkerei erstellen</a>
</p>
<div class="row">
    @foreach (var apiary in Model)
    {
        await Html.RenderPartialAsync("_ApiaryCard", apiary);
    }
</div>

HiveCare1/Views/Apiaries/_LocationsList.cshtml
@using HiveCare1.Controllers
@model List<Location>
<div class="row" id="LocationCards">
    
    @foreach (var location in Model)
    {
        await Html.RenderPartialAsync("_LocationCard", location);
    }

</div>