HiveCare1/Models/Location.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using HiveCare1.Data;
using HiveCare1.Models.Partials;

namespace HiveCare1.Models
{
    public class Location : AddressPartial, IUserDevider
    {
        [Key] public int LocationId { get; set; }
        [NotMapped] public int ApiaryId { get; set; }
        public virtual Apiary Apiary { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Hive> Hives { get; set; } = new List<Hive>();
        public virtual ICollection<LocationApplicationUser> Users { get; set; } = new List<LocationApplicationUser>();
        
        [NotMapped] public List<ApplicationUser> Admins
        {
            get
            {
                return Users.Where(x => x.IsAdmin).Select(x => x.ApplicationUser).ToList();
            }
        }

        [NotMapped] public List<ApplicationUser> Beekeepers { get => Users.Where(x => !x.IsAdmin).Select(x => x.ApplicationUser).ToList(); }
    }
}

HiveCare1/Areas/Identity/Pages/AdminPage/Edit.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using HiveCare1.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HiveCare1.Areas.Identity.Pages.AdminPage
{
    public class EditModel : PageModel
    {
        private readonly ApplicationUserManager _userManager;


        public EditModel(
            ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }

        //public EditModel(
        //    ApplicationUserManager userManager,
        //    ApplicationUsers user)
        //{
        //    _userManager = userManager;
        //    Input = new InputModel();
        //    Input.Email = user.Email;
        //    Input.City = user.City;
        //    Input.ConfirmPassword = user.Password;
        //    Input.Password = user.Password;
        //    Input.Familyname = user.Familyname;
        //    Input.Firstname = user.Firstname;
        //    Input.HouseNo = user.HouseNo;
        //    Input.Street = user.Street;
        //    Input.Zip = Input.Zip;
        //}

        [BindProperty] public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null)
                {
                    return BadRequest();
                }
                user.UserName = Input.Email;
                user.Email = Input.Email ?? user.Email;
                user.Zip = Input.Zip?? user.Zip;
                user.Firstname = Input.Firstname ?? user.Firstname;
                user.Familyname = Input.Familyname ?? user.Familyname;
                user.City = Input.City ?? user.City;
                user.Street = Input.Street ?? user.Street;
                user.HouseNo = Input.HouseNo ?? user.HouseNo;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded) return LocalRedirect(returnUrl);

                foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }

        public async Task<IActionResult> OnGetAsync(string email)
        {
            var user = await _userManager.FindByEmailAsync(email);
            if (user == null) return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            Input = new InputModel
            {
                Email = email,
                City = user.City,
                Street = user.Street,
                Familyname = user.Familyname,
                Firstname = user.Firstname,
                Zip = user.Zip,
                HouseNo = user.HouseNo
            };

            return Page();
        }

        public class InputModel
        {
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
                MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            [Display(Name = "First Name")]
            public string Firstname { get; set; }

            [Display(Name = "Name")] public string Familyname { get; set; }

            [Display(Name = "Street")] public string Street { get; set; }

            [Display(Name = "Number")] public string HouseNo { get; set; }

            [Display(Name = "City")] public string City { get; set; }

            [Display(Name = "ZIP")] public string Zip { get; set; }
            [Display(Name = "Imkereien")] public List<int> Apiaries { get; set; }

            [Display(Name = "Standorte")] public List<int> Locations { get; set; }
            [Display(Name = "Bienenvölker")] public List<int> Hives { get; set; }
            public ApplicationUser Creator { get; set; }
        }
    }
}

HiveCare1/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HiveCare1.Data;
using HiveCare1.Models;
using HiveCare1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HiveCare1.Controllers
{
    [Authorize]
    public class LocationsController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly ApplicationUserManager _userManager;
        public LocationsController(ApplicationDbContext context, ApplicationUserManager userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Locations.ToListAsync());
        }
        
        public async Task<IActionResult> Create(int? apiaryid)
        {
            var user = await _userManager.GetCurrentUserAsync();
            if (user.Apiaries.Count > 0 && apiaryid != null)
            {
                return View(new Location()
                {
                    ApiaryId = apiaryid??0,
                    Apiary = await _context.Apiaries.FindAsync(apiaryid),
                });
            }
            else
            {
                return View(new Location());
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("LocationId,Name,Street,HouseNo,Zip,City,Latitude,Longitude,ApiaryId")]
            Location location)
        {
            if (ModelState.IsValid)
            {
                    location.Creator = await _userManager.GetCurrentUserAsync();
                    location.CreatorId = location.Creator.Id;
                    location.CreationDate = DateTime.Now;
                    location.Users.Add(
                        new LocationApplicationUser
                        {
                            LocationId = location.ApiaryId,
                            ApplicationUserId = location.Creator.Id
                        });
                    var apiary = await _context.Apiaries.FirstOrDefaultAsync(x => x.ApiaryId == location.ApiaryId);
                    location.Apiary = apiary;
                    location.Apiary.Locations.Add(location);
                    location.ApiaryId = apiary.ApiaryId;
                    location.Users = new List<LocationApplicationUser>();
                    await SetUsers(location);
                    _context.Add(location);
                    await _context.SaveChangesAsync();
               

                return RedirectToAction(nameof(Index));
            }

            return View(location);
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.LocationId == id);
            if (location == null) return NotFound();

            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var location = await _context.Locations.Include(locati => locati.Creator).Include(loc => loc.Users)
                .Include(l => l.Apiary).Include(loc => loc.Hives).ThenInclude(hive => hive.Queen).FirstOrDefaultAsync(x => x.LocationId == id);
            if (location == null) return NotFound();
            location.ApiaryId = location.Apiary.ApiaryId;
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Name,Street,HouseNo,Zip,City,LocationId,Latitude,Longitude,CreatorId,ApiaryId")]
            Location location)
        {
            var test = Request.Form["ApiaryId"];
            if (id != location.LocationId) return NotFound();
            var dblocation = await _context.Locations.FindAsync(location.LocationId);

            var name = location.Name;
            var locationId = location.LocationId;
            var street = location.Street;
            var houseno = location.HouseNo;
            var zip = location.Zip;
            var city = location.City;
            var lat = location.Latitude;
            var lon = location.Longitude;
            

            if (ModelState.IsValid)
            {
                 var modelToEdit = await _context.Locations
                .Include(location1 => location1.Apiary)
                .Include(location1 => location1.Users)
                .ThenInclude(locationApplicationUser => locationApplicationUser.ApplicationUser)
                .Where(location1 => location1.LocationId == id)
                .FirstOrDefaultAsync();

                 if (modelToEdit.Name != name) modelToEdit.Name = name;
                 if (modelToEdit.Street != street) modelToEdit.Street = street;
                 if (modelToEdit.HouseNo != houseno) modelToEdit.HouseNo = houseno;
                 if (modelToEdit.Zip != zip) modelToEdit.Zip = zip;
                 if (modelToEdit.City != city) modelToEdit.City = city;
                 if (modelToEdit.Latitude != lat) modelToEdit.Latitude = lat;
                 if (modelToEdit.Longitude != lon) modelToEdit.Longitude = lon;

                await SetUsers(modelToEdit);

                try
                {
                    _context.Update(modelToEdit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(modelToEdit.LocationId))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Edit),new {id = modelToEdit.LocationId});
            }

            return View(location);
        }

        private async Task<int> SetUsers(Location modelToEdit)
        {

            var adminEmails = Request.Form["AdminUsers"].ToString().Split(',').Where(x => x != "").ToList();
            var beekeeperEmails = Request.Form["BeekeeperUsers"].ToString().Trim(',').Split(',').Where(x => x != "")
                .ToList();
            var dellist = modelToEdit.Users.Where(user =>
                {
                    var usertest = _context.ApplicationUsers.Find(user.ApplicationUserId);
                    return !adminEmails.Contains(user.ApplicationUser.Email) ||
                           !beekeeperEmails.Contains(user.ApplicationUser.Email);
                }
                ).ToList();

            foreach (var applicationUser in dellist)
                modelToEdit.Users.Remove(applicationUser);

            foreach (var adminEmail in adminEmails)
            {
                var admin = await _userManager.FindByEmailAsync(adminEmail);
                modelToEdit.Users.Add(new LocationApplicationUser()
                {
                    ApplicationUser = admin,
                    ApplicationUserId = admin.Id,
                    Location = modelToEdit,
                    LocationId = modelToEdit.LocationId,
                    IsAdmin = true
                });
            }

            foreach (var email in beekeeperEmails)
            {
                var beekeeper = await _userManager.FindByEmailAsync(email);
                modelToEdit.Users.Add(new LocationApplicationUser()
                {
                    ApplicationUser = beekeeper,
                    ApplicationUserId = beekeeper.Id,
                    Location = modelToEdit,
                    LocationId = modelToEdit.LocationId,
                    IsAdmin = false
                });
            }

            return 1;
        }

        // GET: Locations/Delete/5
            public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.LocationId == id);
            if (location == null) return NotFound();

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _context.Locations.FindAsync(id);
            _context.Locations.Remove(location);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.LocationId == id);
        }

        public async Task<IList<Location>> ListLocationsAsync()
        {
            var user = await _userManager.GetCurrentUserAsync();
            var apiarieLocations = (await _context.ApiaryApplicationUsers
                    .Include(a => a.Apiary)
                    .Where(x => x.ApplicationUserId == user.Id)
                    .ToListAsync())
                .SelectMany(x => x.Apiary.Locations)
                .ToList();

            var directLocations =
                (await _context.Locations.Include(x => x.Users).ToListAsync()).Where(x =>
                    x.Admins.Contains(user)).ToList();

HiveCare1/Views/Locations/Create.cshtml
@model HiveCare1.Models.Location
@inject ApiariesController ApiariesController
@inject ApplicationUserManager UserManager
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
    var apiaries = await ApiariesController.ListApiariesAsync();
    var selectlist = apiaries.Select(x => new SelectListItem(x.Name, x.ApiaryId.ToString()));
}

<h2>Standort Erstellen</h2>
<hr />
<div class="row">
    <div class="col offset-md-2 col-md-8  p-4 shadow flex-grow-1">
        <form id="LocationsCreate" class="p-2 p-md-4" asp-action="Create" asp-controller="Locations">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApiaryId" class="control-label">Imkerei</label>
                @Html.DropDownListFor(location => location.ApiaryId, selectlist, new { @class = "form-control" })
                <span asp-validation-for="ApiaryId" class="text-danger"></span>
            </div>
            <div class="">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Administratoren:</label>
                @{
                    await Html.RenderPartialAsync("_AdministratorsSelect", Model.Admins);
                }
                <hr />
                <label>Imker:</label>
                @{
                    await Html.RenderPartialAsync("_BeekeepersSelect", Model.Beekeepers);
                }
            </div>
            <div class="form-group">
                @{ await Html.RenderPartialAsync("_Address", Model); }
            </div>
            <div class="form-group">
                <input type="submit" value="Standort erstellen" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Zurück zur Liste</a>
</div>

HiveCare1/Views/Locations/Delete.cshtml
@model Location

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="LocationId"/>
        <input type="submit" value="Delete" class="btn btn-default"/> |
        <a asp-action="Index">Zurück zur Liste</a>
    </form>
</div>

HiveCare1/Views/Locations/Details.cshtml
@model Location

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Location</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LocationId">Edit</a> |
    <a asp-action="Index">Zurück zur Liste</a>
</div>

HiveCare1/Views/Locations/Edit.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.EntityFrameworkCore
@model Location

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}
@inject ApiariesController ApiariesController
@inject ApplicationUserManager UserManager
@{
    var apiaries = await ApiariesController.ListApiariesAsync();
    var selectlist = apiaries.Select(x => new SelectListItem(x.Name, x.ApiaryId.ToString(),x.ApiaryId == Model.Apiary.ApiaryId));
}
<h2>Standort bearbeiten</h2>
<hr />
<div class="row">
    <div class="col offset-md-2 col-md-8  p-4 shadow flex-grow-1">
        <form id="LocationForm" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="LocationId" type="hidden" />
            <input asp-for="CreatorId" type="hidden" />
            
            <div class="form-group">
                <label asp-for="ApiaryId" class="control-label">Imkerei</label>
                @Html.TextBoxFor(x => x.Apiary.Name,new {disabled = "disabled",@class="form-control"})
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Adress</label>
                @{
                    await Html.RenderPartialAsync("_Address", Model);
                }


            </div>
            <div class="form-group">
                <div class="row">
                    @{
                        ViewData["size"] = "col-12";
                        ViewData["bodyhidden"] = "d-none";
                    }
                    <label>Administratoren:</label>
                    @{
                        await Html.RenderPartialAsync("_AdministratorsSelect", Model.Admins);
                    }
                    <hr />
                    <label>Imker:</label>
                    @{
                        await Html.RenderPartialAsync("_BeekeepersSelect", Model.Beekeepers);
                    }
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Speichern" class="btn btn-default" />
            </div>
        </form>
    </div>

    <div class="col col-md-8 offset-md-2 p-4">
        <h5>
            Bienenvölker
        </h5>
        
        @{
            @Html.ActionLink("Neues Bienenvolk erstellen","Create","Hives",new {locationid = Model.LocationId})
            await Html.RenderPartialAsync("_HivesList", Model.Hives.ToList());
        }
    </div>

</div>

<div>
    <a asp-action="Index">Zurück zur Liste</a>
</div>

@section ScriptsBody
    {
    <script type="text/javascript">
        $(document).ready(function () {
            //hivecare.showMap("forceMap", { action: "edit", type: "locations" });
        })
    </script>
}

HiveCare1/Views/Locations/Index.cshtml
@model IEnumerable<Location>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutExtensionLoggedin.cshtml";
}

<h2>Index</h2>


<p>
    <a asp-action="Create">Neuen Standort erstellen</a>
</p>
<div class="row">
    @foreach (var apiary in Model)
    {
        await Html.RenderPartialAsync("_LocationCard", apiary);
    }
</div>