HiveCare1/Areas/Identity/Pages/_Layout.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HiveCare1.Areas.Identity.Pages
{
    public class _LayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HiveCare1/Controllers/HivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HiveCare1.Data;
using HiveCare1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HiveCare1.Controllers
{
    public class HivesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ApplicationUserManager _userManager;

        public HivesController(ApplicationDbContext context, ApplicationUserManager userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Hives
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetCurrentUserAsync();
            var isSu = await _userManager.IsInRoleAsync(user, "Superuser");
            return View(await _context.Hives
                .Include(hive => hive.Queen)
                .Include(hive => hive.Location)
                .ThenInclude(x => x.Apiary)
                .Include(hive => hive.Location.Users)
                .ThenInclude(applicationUser => applicationUser.ApplicationUser)
                .Include(hive => hive.Users)
                .ThenInclude(applicationUser => applicationUser.ApplicationUser)
                .Where(x => x.Admins.Contains(user) || isSu || x.Location.Admins.Contains(user)).ToListAsync()
            );
        }

        // GET: Hives/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var hive = await _context.Hives
                .FirstOrDefaultAsync(m => m.HiveId == id);
            if (hive == null) return NotFound();

            return View(hive);
        }

        // GET: Hives/Create
        public async Task<IActionResult> Create(int? locationid)
        {
            if (locationid != null)
            {
                return View(new Hive()
                {
                    LocationId = locationid??0,
                    Location = await _context.Locations.FindAsync(locationid)
                });
            }
            return View();
        }

        // POST: Hives/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind(
                "HiveId,Name,Type,QueenBirthYear,QueenNo,QueenPainted,Gentleness,Loyalty,Inertia,Aggressiveness,LocationId")]
            Hive hive, int? locationid)
        {
            hive.Creator = await _userManager.GetCurrentUserAsync();
            hive.CreatorId = hive.Creator.Id;
            hive.CreationDate = DateTime.Now;

            hive.Location =
                await _context.Locations.FirstOrDefaultAsync(location => location.LocationId == hive.LocationId);
            hive.Location.Hives.Add(hive);
            if (ModelState.IsValid)
            {
                await SetUsers(hive);
                _context.Add(hive);
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Edit),new {id = hive.HiveId});
            }

            return View(hive);
        }

        private async Task<int> SetUsers(Hive modelToEdit)
        {

            var adminEmails = Request.Form["AdminUsers"].ToString().Split(',').Where(x => x != "").ToList();
            var beekeeperEmails = Request.Form["BeekeeperUsers"].ToString().Trim(',').Split(',').Where(x => x != "")
                .ToList();
            var dellist = modelToEdit.Users.Where(user =>
                !adminEmails.Contains(user.ApplicationUser.Email) ||
                !beekeeperEmails.Contains(user.ApplicationUser.Email)).ToList();

            foreach (var applicationUser in dellist)
                modelToEdit.Users.Remove(applicationUser);

            foreach (var adminEmail in adminEmails)
            {
                var admin = await _userManager.FindByEmailAsync(adminEmail);
                modelToEdit.Users.Add(new HiveApplicationUser()
                {
                    ApplicationUser = admin,
                    ApplicationUserId = admin.Id,
                    Hive = modelToEdit,
                    HiveId = modelToEdit.HiveId,
                    IsAdmin = true
                });
            }

            foreach (var email in beekeeperEmails)
            {
                var beekeeper = await _userManager.FindByEmailAsync(email);
                modelToEdit.Users.Add(new HiveApplicationUser()
                {
                    ApplicationUser = beekeeper,
                    ApplicationUserId = beekeeper.Id,
                    Hive = modelToEdit,
                    HiveId = modelToEdit.HiveId,
                    IsAdmin = false
                });
            }

            return 1;
        }

        // GET: Hives/Edit/5
            public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var hive = await _context.Hives
                .Include(hive1 => hive1.Users).ThenInclude(a => a.ApplicationUser)
                .Include(hive1 => hive1.Queen)
                .Include(hive1 => hive1.Location)
                .FirstOrDefaultAsync(hive1 => hive1.HiveId == id);
            if (hive == null) return NotFound();
            return View(hive);
        }

        // POST: Hives/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind(
                "HiveId,Name,Type,Queen.QueenNo,Queen.QueenPainted,Gentleness,Loyalty,Inertia,Aggressiveness,CreationDate,QueenId")]
            Hive hive)
        {
            if (id != hive.HiveId) return NotFound();

            if (ModelState.IsValid)
            {
                //hive.Users = await _context.HiveApplicationUsers.Where(x => x.HiveId == id).ToListAsync();
               
                hive.Queen = await _context.Queens.FindAsync(hive.QueenId);
                try
                {
                    //var queen = await _context.Queens.FirstOrDefaultAsync(x => x.HiveId == hive.HiveId);
                    if (hive.Queen == null)
                    {
                        var user = await _userManager.GetCurrentUserAsync();
                        hive.Queen = new Queen
                        {
                            Hive = hive,
                            Creator = user,
                            CreationDate = DateTime.Now,
                            CreatorId = user.Id
                        };
                    }

                    hive.Queen.QueenBirthYear = Convert.ToInt32(Request.Form["QueenBirthYear"]);
                    hive.Queen.QueenNo = Convert.ToInt32(Request.Form["QueenNo"]);
                    hive.Queen.QueenPainted = Convert.ToBoolean(Request.Form["QueenPainted"]);
                    _context.Queens.Update(hive.Queen);
                    await SetUsers(hive);
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HiveExists(hive.HiveId))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Edit),hive.HiveId);
            }

            return View(hive);
        }

        // GET: Hives/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var hive = await _context.Hives
                .FirstOrDefaultAsync(m => m.HiveId == id);
            if (hive == null) return NotFound();

            return View(hive);
        }

        // POST: Hives/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hive = await _context.Hives.FindAsync(id);
            _context.Hives.Remove(hive);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HiveExists(int id)
        {
            return _context.Hives.Any(e => e.HiveId == id);
        }

        public async Task<IEnumerable<SelectListItem>> GetListAsync()
        {
            return await _context.Hives.Select(x => new SelectListItem(x.Name, x.HiveId.ToString())).ToListAsync();
        }

        public async Task<IEnumerable<Hive>> ListHivessAsync()
        {
            var user = await _userManager.GetCurrentUserAsync();
            var isSu = await _userManager.IsInRoleAsync(user, "Superuser");
            return await _context.Hives
                .Include(hive => hive.Users)
                .Include(hive => hive.Creator)
                .Include(hive => hive.Location)
                .ThenInclude(location => location.Apiary)
                .Where(hive => hive.Users.Any(admin => admin.ApplicationUserId == user.Id) ||hive.Location.Users.Any(admin => admin.ApplicationUserId == user.Id)||hive.Location.Apiary.Users.Any(admin => admin.ApplicationUserId == user.Id) ||
                                 hive.Creator.Id == user.Id || isSu)
                .ToListAsync();
            
        }
        public async Task<IEnumerable<Hive>> ListHivesForLocationAsync(int? locationid)
        {
            var user = await _userManager.GetCurrentUserAsync();
            var isSu = await _userManager.IsInRoleAsync(user, "Superuser");
            return await _context.Hives
                .Include(hive => hive.Users)

HiveCare1/Views/Shared/_AdministratorUserCard.cshtml
@using System.Globalization
@using Microsoft.CodeAnalysis.Differencing
@model HiveCare1.Models.ApplicationUser
@inject ApplicationUserManager ApplicationUserManager
@{ var userrole = await ApplicationUserManager.GetRolesAsync(Model); }
<div class="@(ViewData["size"]??"") hccard" data-email="@Model.Email">
    <div class="card my-1">
        <div class="card-header p-0 ">
            <span class="font-weight-bold">

                <div class="dropdown w-100 d-inline-flex">
                    @if (ViewContext.ActionDescriptor.RouteValues["action"].Equals("Edit") || ViewContext.ActionDescriptor.RouteValues["action"].Equals("Create"))
                    {
                        <button class="btn btn-light dropdown-toggle font-weight-bold" type="button" id="dropdownActions@(Model.Email.GetHashCode())" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="34px" viewBox="9 9 20 20">
                                <path d="M12 4a5 5 0 1 1-5 5 5 5 0 0 1 5-5m0-2a7 7 0 1 0 7 7 7 7 0 0 0-7-7zm10 28h-2v-5a5 5 0 0 0-5-5H9a5 5 0 0 0-5 5v5H2v-5a7 7 0 0 1 7-7h6a7 7 0 0 1 7 7zm3-13.82l-2.59-2.59L21 15l4 4 7-7-1.41-1.41L25 16.18z" />
                            </svg>
                            <span>@((Model.Firstname + " " + Model.Familyname).ToUpper(CultureInfo.CurrentCulture))</span>
                        </button>
                    }
                    else
                    {
                        <button class="btn btn-light font-weight-bold" type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="34px" viewBox="9 9 20 20">
                                <path d="M12 4a5 5 0 1 1-5 5 5 5 0 0 1 5-5m0-2a7 7 0 1 0 7 7 7 7 0 0 0-7-7zm10 28h-2v-5a5 5 0 0 0-5-5H9a5 5 0 0 0-5 5v5H2v-5a7 7 0 0 1 7-7h6a7 7 0 0 1 7 7zm3-13.82l-2.59-2.59L21 15l4 4 7-7-1.41-1.41L25 16.18z" />
                            </svg>
                            <span>@((Model.Firstname + " " + Model.Familyname).ToUpper(CultureInfo.CurrentCulture))</span>
                        </button>
                    }

                    @if (ViewContext.ActionDescriptor.RouteValues["action"].Equals("Edit") || ViewContext.ActionDescriptor.RouteValues["action"].Equals("Create"))
                    {
                        <div class="dropdown-menu" aria-labelledby="dropdownActions@(Model.Email.GetHashCode())">
                            <a onclick="return hivecare.removeAdmin(event)" class="dropdown-item">Entfernen</a>
                        </div>
                    }
                    else
                    {
                        <div class="dropdown-menu" aria-labelledby="dropdownActions@(Model.Email.GetHashCode())">
                        </div>
                    }

                </div>
            </span>
        </div>
        @if (!ViewContext.ActionDescriptor.RouteValues["action"].Equals("Edit") && !ViewContext.ActionDescriptor.RouteValues["action"].Equals("Create"))
        {
            <div class="card-body @(ViewData["bodyhidden"] ?? "")">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <span class="d-inline-block w-100"><label class="font-weight-bold">Benutzername(Email): </label><span class="d-inline-flex align-top float-right">@Model.UserName</span></span>
                        </div>
                        <div class="col-12">
                            <span class="d-inline-block w-100">
                                <label class="font-weight-bold">Adresse: </label>
                                <span class="d-inline-flex align-top float-right">
                                    @(Model.Street + " " + Model.HouseNo) <br />
                                    @(Model.Zip + " " + Model.City)
                                </span>
                            </span>
                        </div>
                        <div class="col-12">
                            <span class="d-inline-block w-100">
                                <label class="font-weight-bold">Role:</label>
                                <span class="d-inline-flex align-top float-right">
                                    @userrole.FirstOrDefault()
                                </span>
                            </span>
                        </div>
                        <div class="col-12">
                            <span class="d-inline-block w-100">
                                <label class="font-weight-bold">Opeations:</label>
                                <span class="d-inline-flex align-top float-right">
                                    <span><a href="@Url.Page("/AdminPage/Edit", new {email = Model.Email})">Edit</a></span>
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

HiveCare1/Views/Shared/_ApiaryCard.cshtml
@using System.Globalization
@model Apiary

<div class="apiarycard col-12 col-md-6 py-2" data-apiary="@Model.ApiaryId">
    <div class="card">
        <div class="card-header">
            <span class="font-weight-bold">

                <div class="dropdown d-inline-flex">
                    <button class="btn btn-light dropdown-toggle font-weight-bold" type="button" id="dropdownApiaryActions@( Model.ApiaryId )" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="34px" viewBox="15 0 25 25" style="transform: rotate(45deg);">
                            <path d="M16 10a6 6 0 0 0-6 6v8a6 6 0 0 0 12 0v-8a6 6 0 0 0-6-6zm-4.25 7.87h8.5v4.25h-8.5zM16 28.25A4.27 4.27 0 0 1 11.75 24v-.13h8.5V24A4.27 4.27 0 0 1 16 28.25zm4.25-12.13h-8.5V16a4.25 4.25 0 0 1 8.5 0zm10.41 3.09L24 13v9.1a4 4 0 0 0 8 0 3.83 3.83 0 0 0-1.34-2.89zM28 24.35a2.25 2.25 0 0 1-2.25-2.25V17l3.72 3.47A2.05 2.05 0 0 1 30.2 22a2.25 2.25 0 0 1-2.2 2.35zM0 22.1a4 4 0 0 0 8 0V13l-6.66 6.21A3.88 3.88 0 0 0 0 22.1zm2.48-1.56L6.25 17v5.1a2.25 2.25 0 0 1-4.5 0 2.05 2.05 0 0 1 .73-1.56zM15 5.5A3.5 3.5 0 1 0 11.5 9 3.5 3.5 0 0 0 15 5.5zm-5.25 0a1.75 1.75 0 1 1 1.75 1.75A1.77 1.77 0 0 1 9.75 5.5zM20.5 2A3.5 3.5 0 1 0 24 5.5 3.5 3.5 0 0 0 20.5 2zm0 5.25a1.75 1.75 0 1 1 1.75-1.75 1.77 1.77 0 0 1-1.75 1.75z" />
                        </svg>
                        @Model.Name?.ToUpper(CultureInfo.CurrentCulture)
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownApiaryActions@(Model.ApiaryId)">
                        <a href="@Url.Action("Edit","Apiaries",new {id = Model.ApiaryId})" class="dropdown-item">Bearbeiten</a>
                        <a href="@Url.Action("Delete","Apiaries",new {id = Model.ApiaryId})" class="dropdown-item">Löschen</a>
                    </div>
                </div>
            </span>

        </div>
        <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 hover-light">
                        <span class="d-inline-block w-100">
                            <label class="font-weight-bold">Standorte: </label>
                            <span class="d-inline-flex align-top float-right">
                                @Model.Locations.Count
                            </span>
                        </span>
                    </div>
                    <div class="col-12 hover-light">
                        <span class="d-inline-block w-100">
                            <label class="font-weight-bold">Bienenvölker:</label>
                            <span class="d-inline-flex align-top float-right">
                                @Model.Locations.Sum(x => x.Hives.Count())
                            </span>
                        </span>
                    </div>
                    <div class="col-12 hover-light">
                        <span class="d-inline-block w-100">
                            <label class="font-weight-bold">Erträge:</label>
                            <span class="d-inline-flex align-top float-right">
                                @Model.Locations.Sum(x => x.Hives.Sum(hive => hive.YieldAmounts.Count))
                            </span>
                        </span>  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HiveCare1/Views/Shared/_BeekeeperUserCard.cshtml
@using System.Globalization
@model ApplicationUser
@inject ApplicationUserManager ApplicationUserManager
@{ var userrole = await ApplicationUserManager.GetRolesAsync(Model); }
<div class="@(ViewData["size"]??"") hccard" data-email="@Model.Email">
    <div class="card my-1">
        <div class="card-header p-0 ">
            <span class="font-weight-bold">

                <div class="dropdown w-100 d-inline-flex">
                    @if (ViewContext.ActionDescriptor.RouteValues["action"].Equals("Edit") || ViewContext.ActionDescriptor.RouteValues["action"].Equals("Create"))
                    {
                        <button class="btn btn-light dropdown-toggle font-weight-bold" type="button" id="dropdownActions@(Model.Email.GetHashCode())" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="34px" viewBox="9 9 20 20">
                                <path d="M16 4a5 5 0 1 1-5 5 5 5 0 0 1 5-5m0-2a7 7 0 1 0 7 7 7 7 0 0 0-7-7zm10 28h-2v-5a5 5 0 0 0-5-5h-6a5 5 0 0 0-5 5v5H6v-5a7 7 0 0 1 7-7h6a7 7 0 0 1 7 7z" />
                            </svg>
                            <span>@((Model.Firstname + " " + Model.Familyname).ToUpper(CultureInfo.CurrentCulture))</span>
                        </button>
                    }
                    else
                    {
                        <button class="btn btn-light font-weight-bold" type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="34px" viewBox="9 9 20 20">
                                <path d="M16 4a5 5 0 1 1-5 5 5 5 0 0 1 5-5m0-2a7 7 0 1 0 7 7 7 7 0 0 0-7-7zm10 28h-2v-5a5 5 0 0 0-5-5h-6a5 5 0 0 0-5 5v5H6v-5a7 7 0 0 1 7-7h6a7 7 0 0 1 7 7z" />
                            </svg>
                            <span>@((Model.Firstname + " " + Model.Familyname).ToUpper(CultureInfo.CurrentCulture))</span>
                        </button>
                    }

                    @if (ViewContext.ActionDescriptor.RouteValues["action"].Equals("Edit") || ViewContext.ActionDescriptor.RouteValues["action"].Equals("Create"))
                    {
                        <div class="dropdown-menu" aria-labelledby="dropdownActions@(Model.Email.GetHashCode())">
                            <a onclick="return hivecare.removeAdmin(event)" class="dropdown-item">Entfernen</a>
                        </div>
                    }
                    else
                    {
                        <div class="dropdown-menu" aria-labelledby="dropdownActions@(Model.Email.GetHashCode())">
                        </div>
                    }

                </div>
            </span>
        </div>
    @if (!ViewContext.ActionDescriptor.RouteValues["action"].Equals("Edit") && !ViewContext.ActionDescriptor.RouteValues["action"].Equals("Create"))
    {
        <div class="card-body @(ViewData["bodyhidden"] ?? "")">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <span class="d-inline-block w-100"><label class="font-weight-bold">Benutzername(Email): </label><span class="d-inline-flex align-top float-right">@Model.UserName</span></span>
                    </div>
                    <div class="col-12">
                        <span class="d-inline-block w-100">
                            <label class="font-weight-bold">Adresse: </label>
                            <span class="d-inline-flex align-top float-right">
                                @(Model.Street + " " + Model.HouseNo) <br/>
                                @(Model.Zip + " " + Model.City)
                            </span>
                        </span>
                    </div>
                    <div class="col-12">
                        <span class="d-inline-block w-100">
                            <label class="font-weight-bold">Role:</label>
                            <span class="d-inline-flex align-top float-right">
                                @userrole.FirstOrDefault()
                            </span>
                        </span>
                    </div>
                    <div class="col-12">
                        <span class="d-inline-block w-100">
                            <label class="font-weight-bold">Opeations:</label>
                            <span class="d-inline-flex align-top float-right">
                                <span><a href="@Url.Page("/AdminPage/Edit", new {email = Model.Email})">Edit</a></span>
                            </span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    }
    </div>
</div>

HiveCare1/Views/Shared/_BeekeepersSelect.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.EntityFrameworkCore
@using Microsoft.EntityFrameworkCore.Internal
@model List<ApplicationUser>
@inject ApplicationUserManager UserManager
@{
    var users = await UserManager.Users.ToListAsync();
    if (!User.IsInRole("Superuser")) {
        users = users.Where(user => user.Creator.Id == User.Identity.Name).ToList();
    }

    IEnumerable<SelectListItem> selectlist = new List<SelectListItem>();
    if (users.Count > 0)
    {
        selectlist = users.Select(x => new SelectListItem(x.Firstname + " " + x.Familyname, x.Email + ""));
    }
}

@Html.Hidden("RemoveAdmin", "")
@Html.DropDownList("BeekeeperUsers", users.Select(x => new SelectListItem{
            Selected = Model.Contains(x),
            Text = x.Firstname+" "+x.Familyname,
            Value = x.Email

        }
        ).ToList(), new { @class = "form-control selectpicker", multiple = "multiple"})

HiveCare1/Views/Shared/_CreateFeed.cshtml
@model HiveCare1.Models.Feed


<div class="card shadow">
    <div class="card-header">
        <button class="btn btn-light" type="button" data-toggle="collapse" data-target="#collapseFeed@(Model.FeedId)" aria-expanded="false" aria-controls="collapseFeed@(Model.FeedId)">
            Neue Fütterung am @DateTime.Now
        </button>
    </div>
    <div class="collapse show" id="collapseFeed@(Model.FeedId)">
        <div class="card-body">
            <form asp-action="AddFeed" asp-controller="BeekeepingApi" class="my-1 feedCreateForm">
                
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12 col-md-5">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="HiveId" />
                            <div class="form-group">
                                <label asp-for="FeedType" class="control-label"></label>
                                @{
                                    var selects = Html.GetEnumSelectList(typeof(FeedTypeEnum)).ToList();
                                    selects.ForEach(x => x.Selected = Model.FeedType.ToString() == x.Value);
                                    @Html.DropDownListFor(x => x.FeedType, selects, new {@class = "form-control"})
                                    ;

                                }
                                <span asp-validation-for="FeedType" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Amout" class="control-label"></label>
                                <input asp-for="Amout" class="form-control"/>
                                <span asp-validation-for="Amout" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CreationDate" class="control-label"></label>
                                <input asp-for="CreationDate" class="form-control"/>
                                <span asp-validation-for="CreationDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Fütterung erstellen" class="btn btn-primary"/>
                            </div>
                        </div>
                        <div class="col-12 col-md-7">
                            <div class="form-group">
                                <label asp-for="Comment" class="control-label"></label>
                                <textarea asp-for="Comment" class="form-control" rows="15"></textarea>
                                <span asp-validation-for="Comment" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DueDateTime" class="control-label"></label>
                                <input asp-for="DueDateTime" class="form-control"/>
                                <span asp-validation-for="DueDateTime" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DoneDateTime" class="control-label"></label>
                                <input asp-for="DoneDateTime" class="form-control"/>
                                <span asp-validation-for="DoneDateTime" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DoneById" class="control-label"></label>
                                <select asp-for="DoneById" class="form-control" asp-items="ViewBag.DoneById"></select>
                                <span asp-validation-for="DoneById" class="text-danger"></span>
                            </div>
                            <div class="form-group form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" asp-for="IsDone"/> @Html.DisplayNameFor(model => model.IsDone)
                                </label>
                            </div>
                            <div class="form-group">
                                <label asp-for="CreationDate" class="control-label"></label>
                                <input asp-for="CreationDate" class="form-control" disabled="disabled"/>
                                <span asp-validation-for="CreationDate" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HiveCare1/Views/Shared/_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

HiveCare1/Views/Shared/_menuExtension.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject ApplicationUserManager UserManager

@if (User.IsInRole("Administrator") || User.IsInRole("Superuser"))
{
    <li class="nav-item ">
        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">Dashboard</a>
    </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="menuExtension" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Qicklinks</a>
        <ul class="dropdown-menu" aria-labelledby="menuExtension">

            <li>
                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Register User</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Hives" asp-action="Create">Neues Bienenvolk</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Locations" asp-action="Create">Neuer Standort</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Apiaries" asp-action="Create">Neue Imkerei</a>
            </li>
            <li>
            <a class="dropdown-item" href="/Admin/CreateYield">Erträge zusammenführen</a>
                @Html.ActionLink("add","CreateYield","Admin")
            </li>
        </ul>
    </li>
}